# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1175, 827)
        MainWindow.setAnimated(True)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.confiGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.confiGroup.sizePolicy().hasHeightForWidth())
        self.confiGroup.setSizePolicy(sizePolicy)
        self.confiGroup.setMinimumSize(QtCore.QSize(420, 210))
        self.confiGroup.setMaximumSize(QtCore.QSize(420, 210))
        self.confiGroup.setObjectName("confiGroup")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.confiGroup)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.runButton = QtWidgets.QPushButton(self.confiGroup)
        self.runButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.runButton.sizePolicy().hasHeightForWidth())
        self.runButton.setSizePolicy(sizePolicy)
        self.runButton.setMinimumSize(QtCore.QSize(120, 30))
        self.runButton.setMaximumSize(QtCore.QSize(120, 30))
        self.runButton.setAutoDefault(False)
        self.runButton.setDefault(False)
        self.runButton.setFlat(False)
        self.runButton.setObjectName("runButton")
        self.gridLayout_2.addWidget(self.runButton, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(297, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.inputDir = QtWidgets.QLineEdit(self.confiGroup)
        self.inputDir.setObjectName("inputDir")
        self.gridLayout.addWidget(self.inputDir, 0, 3, 1, 1)
        self.inputCoverage = QtWidgets.QLineEdit(self.confiGroup)
        self.inputCoverage.setObjectName("inputCoverage")
        self.gridLayout.addWidget(self.inputCoverage, 3, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(13, 18, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.inputDirBrowseButton = QtWidgets.QPushButton(self.confiGroup)
        self.inputDirBrowseButton.setObjectName("inputDirBrowseButton")
        self.gridLayout.addWidget(self.inputDirBrowseButton, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.confiGroup)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.confiGroup)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.confiGroup)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.confiGroup)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.inputName = QtWidgets.QLineEdit(self.confiGroup)
        self.inputName.setObjectName("inputName")
        self.gridLayout.addWidget(self.inputName, 1, 3, 1, 1)
        self.inputFeature = QtWidgets.QLineEdit(self.confiGroup)
        self.inputFeature.setObjectName("inputFeature")
        self.gridLayout.addWidget(self.inputFeature, 2, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 2)
        self.verticalLayout.addWidget(self.confiGroup)
        self.repairGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repairGroup.sizePolicy().hasHeightForWidth())
        self.repairGroup.setSizePolicy(sizePolicy)
        self.repairGroup.setMinimumSize(QtCore.QSize(420, 400))
        self.repairGroup.setMaximumSize(QtCore.QSize(420, 400))
        self.repairGroup.setCheckable(False)
        self.repairGroup.setObjectName("repairGroup")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.repairGroup)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.bounGroup = QtWidgets.QGroupBox(self.repairGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bounGroup.sizePolicy().hasHeightForWidth())
        self.bounGroup.setSizePolicy(sizePolicy)
        self.bounGroup.setMinimumSize(QtCore.QSize(400, 115))
        self.bounGroup.setMaximumSize(QtCore.QSize(400, 115))
        self.bounGroup.setFlat(False)
        self.bounGroup.setCheckable(True)
        self.bounGroup.setObjectName("bounGroup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.bounGroup)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.bounRadio = QtWidgets.QRadioButton(self.bounGroup)
        self.bounRadio.setEnabled(True)
        self.bounRadio.setChecked(True)
        self.bounRadio.setObjectName("bounRadio")
        self.gridLayout_3.addWidget(self.bounRadio, 0, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(self.bounGroup)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 1, 0, 1, 1)
        self.bounSpinbox = QtWidgets.QSpinBox(self.bounGroup)
        self.bounSpinbox.setMinimum(1)
        self.bounSpinbox.setMaximum(5)
        self.bounSpinbox.setObjectName("bounSpinbox")
        self.gridLayout_3.addWidget(self.bounSpinbox, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(6, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.bounInGlayout = QtWidgets.QGridLayout()
        self.bounInGlayout.setObjectName("bounInGlayout")
        self.bounFileRadio = QtWidgets.QRadioButton(self.bounGroup)
        self.bounFileRadio.setEnabled(True)
        self.bounFileRadio.setMinimumSize(QtCore.QSize(0, 0))
        self.bounFileRadio.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bounFileRadio.setObjectName("bounFileRadio")
        self.bounInGlayout.addWidget(self.bounFileRadio, 0, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(13, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.bounInGlayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.bounFileBrowseButton = QtWidgets.QPushButton(self.bounGroup)
        self.bounFileBrowseButton.setEnabled(False)
        self.bounFileBrowseButton.setMaximumSize(QtCore.QSize(75, 16777215))
        self.bounFileBrowseButton.setObjectName("bounFileBrowseButton")
        self.bounInGlayout.addWidget(self.bounFileBrowseButton, 1, 1, 1, 1)
        self.bounFileInput = QtWidgets.QLineEdit(self.bounGroup)
        self.bounFileInput.setEnabled(False)
        self.bounFileInput.setMaximumSize(QtCore.QSize(120, 16777215))
        self.bounFileInput.setObjectName("bounFileInput")
        self.bounInGlayout.addWidget(self.bounFileInput, 1, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.bounInGlayout)
        self.gridLayout_6.addWidget(self.bounGroup, 0, 0, 1, 2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem5, 1, 0, 1, 2)
        self.failGroup = QtWidgets.QGroupBox(self.repairGroup)
        self.failGroup.setMinimumSize(QtCore.QSize(400, 70))
        self.failGroup.setMaximumSize(QtCore.QSize(400, 70))
        self.failGroup.setCheckable(True)
        self.failGroup.setObjectName("failGroup")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.failGroup)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.failOutCheckbox = QtWidgets.QCheckBox(self.failGroup)
        self.failOutCheckbox.setObjectName("failOutCheckbox")
        self.horizontalLayout_3.addWidget(self.failOutCheckbox)
        self.failDirBrowseButton = QtWidgets.QPushButton(self.failGroup)
        self.failDirBrowseButton.setEnabled(False)
        self.failDirBrowseButton.setObjectName("failDirBrowseButton")
        self.horizontalLayout_3.addWidget(self.failDirBrowseButton)
        self.failDir = QtWidgets.QLineEdit(self.failGroup)
        self.failDir.setEnabled(False)
        self.failDir.setObjectName("failDir")
        self.horizontalLayout_3.addWidget(self.failDir)
        self.gridLayout_6.addWidget(self.failGroup, 2, 0, 1, 2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem6, 3, 0, 1, 2)
        self.ppGroup = QtWidgets.QGroupBox(self.repairGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ppGroup.sizePolicy().hasHeightForWidth())
        self.ppGroup.setSizePolicy(sizePolicy)
        self.ppGroup.setMinimumSize(QtCore.QSize(400, 105))
        self.ppGroup.setMaximumSize(QtCore.QSize(400, 105))
        self.ppGroup.setFlat(False)
        self.ppGroup.setCheckable(True)
        self.ppGroup.setChecked(False)
        self.ppGroup.setObjectName("ppGroup")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.ppGroup)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.ppGroup)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.ppSpinbox = QtWidgets.QSpinBox(self.ppGroup)
        self.ppSpinbox.setMinimum(5)
        self.ppSpinbox.setMaximum(100)
        self.ppSpinbox.setSingleStep(5)
        self.ppSpinbox.setProperty("value", 5)
        self.ppSpinbox.setObjectName("ppSpinbox")
        self.gridLayout_4.addWidget(self.ppSpinbox, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem7, 0, 2, 1, 1)
        self.ppOutCheckbox = QtWidgets.QCheckBox(self.ppGroup)
        self.ppOutCheckbox.setObjectName("ppOutCheckbox")
        self.gridLayout_4.addWidget(self.ppOutCheckbox, 1, 0, 1, 1)
        self.ppDirBrowseButton = QtWidgets.QPushButton(self.ppGroup)
        self.ppDirBrowseButton.setEnabled(False)
        self.ppDirBrowseButton.setObjectName("ppDirBrowseButton")
        self.gridLayout_4.addWidget(self.ppDirBrowseButton, 1, 1, 1, 1)
        self.ppDir = QtWidgets.QLineEdit(self.ppGroup)
        self.ppDir.setEnabled(False)
        self.ppDir.setObjectName("ppDir")
        self.gridLayout_4.addWidget(self.ppDir, 1, 2, 1, 1)
        self.gridLayout_6.addWidget(self.ppGroup, 4, 0, 1, 2)
        spacerItem8 = QtWidgets.QSpacerItem(430, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem8, 5, 0, 1, 1)
        self.execButton = QtWidgets.QPushButton(self.repairGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execButton.sizePolicy().hasHeightForWidth())
        self.execButton.setSizePolicy(sizePolicy)
        self.execButton.setMinimumSize(QtCore.QSize(120, 30))
        self.execButton.setMaximumSize(QtCore.QSize(120, 30))
        self.execButton.setObjectName("execButton")
        self.gridLayout_6.addWidget(self.execButton, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.repairGroup)
        self.reportGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportGroup.sizePolicy().hasHeightForWidth())
        self.reportGroup.setSizePolicy(sizePolicy)
        self.reportGroup.setMinimumSize(QtCore.QSize(420, 81))
        self.reportGroup.setMaximumSize(QtCore.QSize(420, 81))
        self.reportGroup.setObjectName("reportGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.reportGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reportButton = QtWidgets.QPushButton(self.reportGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportButton.sizePolicy().hasHeightForWidth())
        self.reportButton.setSizePolicy(sizePolicy)
        self.reportButton.setMinimumSize(QtCore.QSize(0, 35))
        self.reportButton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.reportButton.setObjectName("reportButton")
        self.horizontalLayout.addWidget(self.reportButton)
        self.exitButton = QtWidgets.QPushButton(self.reportGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(0, 35))
        self.exitButton.setMaximumSize(QtCore.QSize(16777215, 35))
        self.exitButton.setObjectName("exitButton")
        self.horizontalLayout.addWidget(self.exitButton)
        self.verticalLayout.addWidget(self.reportGroup)
        self.gridLayout_7.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.consoleBox = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleBox.sizePolicy().hasHeightForWidth())
        self.consoleBox.setSizePolicy(sizePolicy)
        self.consoleBox.setMaximumSize(QtCore.QSize(16777215, 120))
        self.consoleBox.setUndoRedoEnabled(False)
        self.consoleBox.setReadOnly(True)
        self.consoleBox.setObjectName("consoleBox")
        self.gridLayout_7.addWidget(self.consoleBox, 2, 0, 1, 3)
        self.plotLayout2 = QtWidgets.QVBoxLayout()
        self.plotLayout2.setObjectName("plotLayout2")
        self.plotBox2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotBox2.sizePolicy().hasHeightForWidth())
        self.plotBox2.setSizePolicy(sizePolicy)
        self.plotBox2.setMinimumSize(QtCore.QSize(100, 0))
        self.plotBox2.setMaximumSize(QtCore.QSize(16777215, 0))
        self.plotBox2.setObjectName("plotBox2")
        self.plotLayout2.addWidget(self.plotBox2)
        self.gridLayout_7.addLayout(self.plotLayout2, 0, 2, 2, 1)
        self.plotLayout1 = QtWidgets.QVBoxLayout()
        self.plotLayout1.setObjectName("plotLayout1")
        self.plotBox1 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotBox1.sizePolicy().hasHeightForWidth())
        self.plotBox1.setSizePolicy(sizePolicy)
        self.plotBox1.setMinimumSize(QtCore.QSize(100, 0))
        self.plotBox1.setMaximumSize(QtCore.QSize(16777215, 0))
        self.plotBox1.setObjectName("plotBox1")
        self.plotLayout1.addWidget(self.plotBox1)
        self.gridLayout_7.addLayout(self.plotLayout1, 0, 1, 2, 1)
        self.spaceLayout = QtWidgets.QVBoxLayout()
        self.spaceLayout.setObjectName("spaceLayout")
        self.gridLayout_7.addLayout(self.spaceLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.bounRadio.toggled['bool'].connect(self.bounSpinbox.setEnabled)
        self.bounFileRadio.toggled['bool'].connect(self.bounFileBrowseButton.setEnabled)
        self.bounFileRadio.toggled['bool'].connect(self.bounFileInput.setEnabled)
        self.exitButton.clicked['bool'].connect(MainWindow.close)
        self.failOutCheckbox.toggled['bool'].connect(self.failDirBrowseButton.setEnabled)
        self.failOutCheckbox.toggled['bool'].connect(self.failDir.setEnabled)
        self.ppOutCheckbox.toggled['bool'].connect(self.ppDirBrowseButton.setEnabled)
        self.ppOutCheckbox.toggled['bool'].connect(self.ppDir.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Coverage Test"))
        self.confiGroup.setTitle(_translate("MainWindow", "Configurations"))
        self.runButton.setText(_translate("MainWindow", "Run Program"))
        self.inputDirBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.label_4.setText(_translate("MainWindow", "Bathymetric Coverage (x 100%)"))
        self.label.setText(_translate("MainWindow", "Line File Directory"))
        self.label_3.setText(_translate("MainWindow", "Feature Size (m)"))
        self.label_2.setText(_translate("MainWindow", "Job Name"))
        self.repairGroup.setTitle(_translate("MainWindow", "Data Analysis"))
        self.bounGroup.setTitle(_translate("MainWindow", "Build Boundary"))
        self.bounRadio.setText(_translate("MainWindow", "Use Current Data"))
        self.label_5.setText(_translate("MainWindow", "Coverage   "))
        self.bounFileRadio.setText(_translate("MainWindow", "Input File"))
        self.bounFileBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.failGroup.setTitle(_translate("MainWindow", "Check Compliance"))
        self.failOutCheckbox.setText(_translate("MainWindow", "Output File"))
        self.failDirBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.ppGroup.setTitle(_translate("MainWindow", "Path Planning"))
        self.label_6.setText(_translate("MainWindow", "Iterations "))
        self.ppOutCheckbox.setText(_translate("MainWindow", "Output File"))
        self.ppDirBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.execButton.setText(_translate("MainWindow", "Execute Task"))
        self.reportGroup.setTitle(_translate("MainWindow", "Closure"))
        self.reportButton.setText(_translate("MainWindow", "Generate Report"))
        self.exitButton.setText(_translate("MainWindow", "Exit Program"))
